version: '3'
services:
  react_app:
    build:
      context: .
    container_name: react_app
    command: "npm run dev"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules